- generate-docs/scripts/package-lock.json
- generate-docs/scripts/package.json
Fix this security issue: https://github.com/OfficeDev/office-js-docs-reference/network/dependencies
> fix lodash security vulnerability

- docs/code-snippets/office-snippets.yaml
- docs/docs-ref-autogen/office/officeextension.loadoption.yml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Word: https://github.com/OfficeDev/office-js-docs/blob/master/reference/word/loadoption.md
OneNote: https://github.com/OfficeDev/office-js-docs/blob/master/reference/onenote/loadoption.md
> add loadoption snippets

- docs/docs-ref-conceptual/requirement-sets/office-add-in-requirement-sets.md
Based on SOT: https://github.com/OfficeDev/Office-Js-Requirement-Sets/blob/master/mapping/requirements_officejs.json
> Update common req. set supported clients and platforms

- docs/docfx.json
Added metadata to docfx.json to point to Office Dev header.
> Added UHF header

- docs/docs-ref-conceptual/manifest/metadata.md
- docs/docs-ref-conceptual/manifest/namespace.md
Adding two files which are parts of the manifest if you are using custom functions: 
- Namespace
- Metadata
> adding two manifest definition files

- docs/docs-ref-conceptual/toc.yml
Sorry, I forgot to do this earlier
> Adding links for metadata and namespace

- generate-docs/schemas/api-extractor.schema.json
Copied from https://dev.office.com/json-schemas/api-extractor/api-extractor.schema.json.
In subsequent PR, I'll update the various .api.json files to replace dev.office.com references with GitHub location.
> add api-extractor schema

- generate-docs/api-extractor-inputs-custom-functions-runtime/api-extractor.json
- generate-docs/api-extractor-inputs-excel/api-extractor.json
- generate-docs/api-extractor-inputs-office-runtime/api-extractor.json
- generate-docs/api-extractor-inputs-office/api-extractor.json
- generate-docs/api-extractor-inputs-onenote/api-extractor.json
- generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_1/api-extractor.json
- generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_2/api-extractor.json
- generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_3/api-extractor.json
- generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_4/api-extractor.json
- generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_5/api-extractor.json
- generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_6/api-extractor.json
- generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_7/api-extractor.json
- generate-docs/api-extractor-inputs-outlook/api-extractor.json
- generate-docs/api-extractor-inputs-visio/api-extractor.json
- generate-docs/api-extractor-inputs-word/api-extractor.json
Ran GenerateDocs.cmd with no issues.
> update to new api-extractor schema location

- .openpublishing.redirection.json
> Redirecting newsletter links (#212)

- .openpublishing.redirection.json
* update redirects
* remove .png
> merge from master - redirections

- docs/docs-ref-autogen/office/office.document.yml
- docs/docs-ref-autogen/office/office.tablebinding.yml
- generate-docs/api-extractor-inputs-office/office.d.ts
- generate-docs/json/office.api.json
- generate-docs/script-inputs/office.d.ts
Removing the extra `<` symbols in the local d.ts and rerunning GenerateDocs. This mirrors the pending DT fix: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30926
> Fix brackets

- docs/code-snippets/excel-snippets.yaml
- docs/docs-ref-autogen/excel/excel.range.yml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Adding a code sample for untrack to the reference docs. It's based on [this office-js-snippets](https://github.com/OfficeDev/office-js-snippets/pull/238) snippet, but without preview code.
> [Excel] (Range) Adding untrack snippet to Excel.range

- docs/docfx.json
- docs/docs-ref-autogen/toc.yml
- generate-docs/scripts/postprocessor.ts
- generate-docs/tools/WhatsNew.ts
- generate-docs/tools/tslint.json
TOC update
LInking fields topic
minor mixes
CATS fixes
> merge to live

- docs/docs-ref-autogen/excel/excel.stylecollection.yml
- docs/docs-ref-autogen/outlook/office.internetheaders.yml
- docs/docs-ref-autogen/outlook/office.mailbox.yml
- generate-docs/GenerateDocs.cmd
- generate-docs/api-extractor-inputs-excel/excel.d.ts
- generate-docs/api-extractor-inputs-outlook/outlook.d.ts
- generate-docs/json/excel.api.json
- generate-docs/json/outlook.api.json
- generate-docs/script-inputs/office.d.ts
Also a small addition to the GenerateDocs script
> Latest changes

- generate-docs/tools/WhatsNew.ts
This makes the function signatures and descriptions equal width for the whole set.
> Better table generation for WhatsNew tool

- generate-docs/tools/WhatsNew.ts
Also fixing a couple comment typos.
> Removing question mark characters from optional parameters

- docs/code-snippets/office-snippets.yaml
- docs/docs-ref-autogen/office/office.document.yml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
This is the same base code as the recent [snippets repo checkin](https://github.com/OfficeDev/office-js-snippets/pull/258). I also cleaned up the comments in the related Document snippet.
> Adding an SVG coercion snippet

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/excel/excel.removeduplicatesresult.yml
- docs/docs-ref-autogen/excel/excel.shape.yml
- docs/docs-ref-autogen/excel/excel.shapecollection.yml
- docs/docs-ref-autogen/excel/excel.textframe.yml
- docs/docs-ref-autogen/office/office.addincommands.event.yml
- docs/docs-ref-autogen/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook/office.appointmentread.yml
- docs/docs-ref-autogen/outlook/office.emailaddressdetails.yml
- docs/docs-ref-autogen/outlook/office.item.yml
- docs/docs-ref-autogen/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook/office.messageread.yml
- docs/docs-ref-autogen/outlook_1_1/office.emailaddressdetails.yml
- docs/docs-ref-autogen/outlook_1_2/office.emailaddressdetails.yml
- docs/docs-ref-autogen/outlook_1_3/office.emailaddressdetails.yml
- docs/docs-ref-autogen/outlook_1_4/office.emailaddressdetails.yml
- docs/docs-ref-autogen/outlook_1_5/office.emailaddressdetails.yml
- docs/docs-ref-autogen/outlook_1_6/office.emailaddressdetails.yml
- docs/docs-ref-autogen/outlook_1_7/office.emailaddressdetails.yml
- generate-docs/api-extractor-inputs-excel-release/excel.d.ts
- generate-docs/api-extractor-inputs-office/office.d.ts
- generate-docs/api-extractor-inputs-outlook/outlook.d.ts
- generate-docs/json/office.api.json
- generate-docs/json/outlook.api.json
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/script-inputs/office.d.ts
- generate-docs/script-inputs/office_preview.d.ts
- generate-docs/script-inputs/script-lab-snippets.yaml
Addresses documentation bug in issue https://github.com/OfficeDev/office-js-docs-reference/issues/332.
Also gets latest d.ts and snippets changes.
> [Outlook] (snippet) Add note to sample about mode restriction

- docs/docfx.json
- generate-docs/tools/WhatsNew.ts
Merging out of band to fix the markdown rendering.
> Merging to live

- docs/docfx.json
Fixes issues reported by March CATS report.
> [Admin] (CATS) Resolve issues - March 2019

- docs/code-snippets/excel-snippets.yaml
- docs/docs-ref-autogen/excel/excel.worksheetchangedeventargs.yml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
This adds context to the sample, showing its use as an event handler.
> Improving Excel.WorksheetChangedEventArgs sample

- docs/code-snippets/excel-snippets.yaml
- docs/docs-ref-autogen/excel/excel.tablechangedeventargs.yml
- docs/docs-ref-autogen/excel/excel.worksheetchangedeventargs.yml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/script-inputs/script-lab-snippets.yaml
> Merge to live!

- docs/docs-ref-autogen/toc.yml
- generate-docs/scripts/postprocessor.ts
[Staging site link](https://review.docs.microsoft.com/en-us/javascript/api/excel?view=office-js&branch=AlexJ-WholeTOC)
@ElizabethSamuel-MSFT, can you look at the Outlook section and confirm this is acceptable?
@kbrandl, would you be able to look over the Excel TOC and give your impressions?
> Restoring TOC visibility to smaller classes and interfaces

- docs/docs-ref-autogen/outlook.yml
- docs/docs-ref-autogen/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook/office.appointmentread.yml
- docs/docs-ref-autogen/outlook/office.categories.yml
- docs/docs-ref-autogen/outlook/office.categorydetails.yml
- docs/docs-ref-autogen/outlook/office.item.yml
- docs/docs-ref-autogen/outlook/office.mailboxenums.categorycolor.yml
- docs/docs-ref-autogen/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook/office.messageread.yml
- docs/docs-ref-autogen/toc.yml
- generate-docs/api-extractor-inputs-outlook/outlook.d.ts
- generate-docs/json/outlook.api.json
- generate-docs/script-inputs/office_preview.d.ts
- generate-docs/scripts/preprocessor.ts
Also updating so Outlook sources from office-js-preview.
> Get latest

- generate-docs/GenerateDocs.cmd
- generate-docs/package-lock.json
- generate-docs/tools/.gitignore
- generate-docs/tools/package-lock.json
- generate-docs/tools/package.json
Open question to @Zlatkovsky or @Rick-Kirkham: why were we deleting the package-lock.json file in this repo?
> Update lodash and add package-lock files

- docs/docs-ref-autogen/office/office.error.yml
- generate-docs/api-extractor-inputs-office/office.d.ts
- generate-docs/json/office.api.json
- generate-docs/script-inputs/office.d.ts
- generate-docs/script-inputs/office_preview.d.ts
- generate-docs/scripts/package-lock.json
This also updates the package-lock file according to some upstream dependencies.
> Refreshing with latest from DT

- docs/code-snippets/visio-snippets.yaml
- docs/docs-ref-autogen/visio/visio.shapeview.yml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
This is in response to Issue #424.
> Correcting Visio ShapeView sample

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/excel/excel.datavalidationrule.yml
- docs/docs-ref-autogen/excel_release/excel.datavalidationrule.yml
- docs/docs-ref-autogen/outlook/office.attachmentcontent.yml
- docs/docs-ref-autogen/outlook/office.item.yml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/script-inputs/script-lab-snippets.yaml
- generate-docs/scripts/package-lock.json
Update getAttachmentContentAsync snippet (see PR https://github.com/OfficeDev/office-js-docs-pr/pull/1073)
> Get latest and update Outlook snippet

- generate-docs/tools/WhatsNew.ts
Small tooling improvements for API set table generation.
> What's New tool ignores more LoadOption code and string literal overloads

- docs/code-snippets/visio-snippets.yaml
- docs/docs-ref-autogen/excel/excel.databarconditionalformat.yml
- docs/docs-ref-autogen/excel/excel.datavalidation.yml
- docs/docs-ref-autogen/excel/excel.pagelayout.yml
- docs/docs-ref-autogen/excel/excel.rangeareas.yml
- docs/docs-ref-autogen/excel/excel.shape.yml
- docs/docs-ref-autogen/excel_release/excel.databarconditionalformat.yml
- docs/docs-ref-autogen/excel_release/excel.datavalidation.yml
- docs/docs-ref-autogen/excel_release/excel.pagelayout.yml
- docs/docs-ref-autogen/excel_release/excel.rangeareas.yml
- docs/docs-ref-autogen/excel_release/excel.shape.yml
- docs/docs-ref-autogen/visio/visio.comment.yml
- docs/docs-ref-autogen/visio/visio.commentcollection.yml
- docs/docs-ref-autogen/visio/visio.datarefreshcompleteeventargs.yml
- docs/docs-ref-autogen/visio/visio.document.yml
- docs/docs-ref-autogen/visio/visio.hyperlinkcollection.yml
- docs/docs-ref-autogen/visio/visio.shape.yml
- docs/docs-ref-autogen/visio/visio.shapedataitem.yml
- docs/docs-ref-autogen/visio/visio.shapedataitemcollection.yml
- docs/docs-ref-autogen/visio/visio.shapeview.yml
- generate-docs/api-extractor-inputs-excel-release/excel.d.ts
- generate-docs/api-extractor-inputs-excel/excel.d.ts
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/script-inputs/office.d.ts
- generate-docs/script-inputs/office_preview.d.ts
- generate-docs/script-inputs/script-lab-snippets.yaml
Some of the old Visio sample code had bad practices around load statements. I also cleaned up a bit of formatting.
> Clean up Visio load statements

- docs/docs-ref-autogen/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel/excel.worksheetsingleclickedeventargs.yml
- docs/docs-ref-autogen/office/office.requirementsetsupport.yml
- generate-docs/api-extractor-inputs-custom-functions-runtime/tsdoc-metadata.json
- generate-docs/api-extractor-inputs-excel-release/tsdoc-metadata.json
- generate-docs/api-extractor-inputs-excel/tsdoc-metadata.json
- generate-docs/api-extractor-inputs-office-runtime/tsdoc-metadata.json
- generate-docs/api-extractor-inputs-office/office.d.ts
- generate-docs/api-extractor-inputs-office/tsdoc-metadata.json
- generate-docs/api-extractor-inputs-onenote/tsdoc-metadata.json
- generate-docs/api-extractor-inputs-outlook/tsdoc-metadata.json
- generate-docs/api-extractor-inputs-powerpoint/tsdoc-metadata.json
- generate-docs/api-extractor-inputs-visio/tsdoc-metadata.json
- generate-docs/api-extractor-inputs-word-release/tsdoc-metadata.json
- generate-docs/api-extractor-inputs-word/tsdoc-metadata.json
- generate-docs/json/custom-functions-runtime.api.json
- generate-docs/json/office-runtime.api.json
- generate-docs/json/office.api.json
- generate-docs/json/onenote.api.json
- generate-docs/json/outlook.api.json
- generate-docs/json/powerpoint.api.json
- generate-docs/json/snippets.yaml
- generate-docs/json/visio.api.json
- generate-docs/json/word.api.json
- generate-docs/json/word_release.api.json
- generate-docs/package-lock.json
- generate-docs/script-inputs/office.d.ts
- generate-docs/script-inputs/office_preview.d.ts
- generate-docs/script-inputs/script-lab-snippets.yaml
- generate-docs/tools/package.json
The latest from Definitely Typed and the office-js-snippets repo. This also fixes the security vulnerability.
> Click event snippets and isSetSupported changes

- docs/docs-ref-autogen/outlook_1_1/outlook/office.diagnostics.yml
- docs/docs-ref-autogen/outlook_1_2/outlook/office.diagnostics.yml
- docs/docs-ref-autogen/outlook_1_3/outlook/office.diagnostics.yml
- docs/docs-ref-autogen/outlook_1_4/outlook/office.diagnostics.yml
- docs/docs-ref-autogen/outlook_1_5/outlook/office.diagnostics.yml
- generate-docs/api-extractor-inputs-outlook-release/Outlook_1_1/Outlook.d.ts
- generate-docs/api-extractor-inputs-outlook-release/Outlook_1_2/Outlook.d.ts
- generate-docs/api-extractor-inputs-outlook-release/Outlook_1_3/Outlook.d.ts
- generate-docs/api-extractor-inputs-outlook-release/Outlook_1_4/Outlook.d.ts
- generate-docs/api-extractor-inputs-outlook-release/Outlook_1_5/Outlook.d.ts
- generate-docs/json/outlook_1_1/Outlook.api.json
- generate-docs/json/outlook_1_2/Outlook.api.json
- generate-docs/json/outlook_1_3/Outlook.api.json
- generate-docs/json/outlook_1_4/Outlook.api.json
- generate-docs/json/outlook_1_5/Outlook.api.json
Related to PR https://github.com/OfficeDev/office-js-docs-pr/pull/1221.
> [Outlook] Revert hosts for older requirement sets

- generate-docs/scripts/postprocessor.ts
- generate-docs/tools/WhatsNew.ts
- generate-docs/tools/package.json
Also updating lodash for security purposes.
> Fixing URL creation logic for underscores in Whats New tool

- docs/docfx.json
Changes to docfx.json settings that specify metadata values in all articles.
> [Admin] (CATS) Fix issues from August 2019 report. 

- docs/docs-ref-autogen/excel/toc.yml
- docs/docs-ref-autogen/excel_1_9/custom-functions-runtime.yml
- docs/docs-ref-autogen/excel_1_9/custom-functions-runtime/customfunctions.cancelableinvocation.yml
- docs/docs-ref-autogen/excel_1_9/custom-functions-runtime/customfunctions.invocation.yml
- docs/docs-ref-autogen/excel_1_9/custom-functions-runtime/customfunctions.streaminginvocation.yml
- docs/docs-ref-autogen/excel_1_9/office-runtime.yml
- docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.dialog.yml
- docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.displaywebdialogoptions.yml
- docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.storage.yml
- docs/docs-ref-autogen/excel_1_9/toc.yml
- generate-docs/json/excel_1_9/custom-functions-runtime.api.json
- generate-docs/json/excel_1_9/office-runtime.api.json
- generate-docs/package-lock.json
- generate-docs/scripts/midprocessor.ts
- generate-docs/scripts/package-lock.json
- generate-docs/scripts/postprocessor.ts
There were two issues:
- The CF docs were no longer be added to the Excel TOC by the postprocessor.
- The Excel 1.9 docs did not have custom functions JSON moved to their folder by the midprocessor.
This PR addresses both those issues.
> [excel] (Custom Functions) Returning Custom Functions docs to the reference TOC

- generate-docs/scripts/postprocessor.ts
This removes some commented out code from the post-processor.
> Removing dead code

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.attachmentcontent.yml
- docs/docs-ref-autogen/outlook/outlook/office.item.yml
- generate-docs/json/office/snippets.yaml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Update based on [Ricky's feedback](https://github.com/OfficeDev/outlook-dev-docs/pull/685#discussion_r319655213).
> [Outlook] (sample) Update AttachmentContent sample

- docs/docs-ref-autogen/excel/excel.yml
- docs/docs-ref-autogen/excel/excel/excel.chartseries.yml
- docs/docs-ref-autogen/excel/excel/excel.chartseriesdimension.yml
- docs/docs-ref-autogen/excel/excel/excel.errorcodes.yml
- docs/docs-ref-autogen/excel/excel/excel.range.yml
- docs/docs-ref-autogen/excel/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel/toc.yml
- docs/docs-ref-autogen/excel_1_7/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_8/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_9/excel/excel.worksheet.yml
- generate-docs/api-extractor-inputs-excel-release/Excel_1_7/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_1_8/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_1_9/excel.d.ts
- generate-docs/api-extractor-inputs-excel/excel.d.ts
- generate-docs/json/excel/snippets.yaml
- generate-docs/json/excel_1_1/snippets.yaml
- generate-docs/json/excel_1_2/snippets.yaml
- generate-docs/json/excel_1_3/snippets.yaml
- generate-docs/json/excel_1_4/snippets.yaml
- generate-docs/json/excel_1_5/snippets.yaml
- generate-docs/json/excel_1_6/snippets.yaml
- generate-docs/json/excel_1_7/snippets.yaml
- generate-docs/json/excel_1_8/snippets.yaml
- generate-docs/json/excel_1_9/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/office.d.ts
- generate-docs/script-inputs/office_preview.d.ts
- generate-docs/script-inputs/script-lab-snippets.yaml
These are the latest updates from Definitely Typed. There's also a snippet correction for `showOutlineLevels`.
> Excel updates

- docs/code-snippets/office-snippets.yaml
Adding @deeagar's promise-wrapped sample from https://github.com/OfficeDev/office-js-docs-pr/issues/1404 to `File.getSliceAsync`.
> Adding promise-wrapped getSliceAsync sample

- docs/docs-ref-autogen/office/office/office.document.yml
- generate-docs/json/office/snippets.yaml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/package-lock.json
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/scripts/package-lock.json
- generate-docs/tools/package-lock.json
This snippet was approved in #540. This PR just includes the running of GenerateDocs.
> Updating with latest snippets

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.contact.yml
- docs/docs-ref-autogen/outlook_1_1/outlook/office.contact.yml
- docs/docs-ref-autogen/outlook_1_2/outlook/office.contact.yml
- docs/docs-ref-autogen/outlook_1_3/outlook/office.contact.yml
- docs/docs-ref-autogen/outlook_1_4/outlook/office.contact.yml
- docs/docs-ref-autogen/outlook_1_5/outlook/office.contact.yml
- docs/docs-ref-autogen/outlook_1_6/outlook/office.contact.yml
- docs/docs-ref-autogen/outlook_1_7/outlook/office.contact.yml
- docs/docs-ref-autogen/outlook_1_8/outlook/office.contact.yml
- generate-docs/json/office/snippets.yaml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Related to https://github.com/OfficeDev/office-js/issues/807.
> [Outlook] (Contact) Add contact example to code sample

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook_1_2/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook_1_2/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook_1_3/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook_1_3/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook_1_4/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook_1_4/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook_1_5/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook_1_5/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook_1_6/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook_1_6/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook_1_7/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook_1_7/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook_1_8/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook_1_8/outlook/office.messagecompose.yml
- generate-docs/json/office/snippets.yaml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Using sample from https://github.com/OfficeDev/office-js-docs-pr/pull/1422.
> [Outlook] (sample) getSelectedDataAsync - handle OWA bug

- docs/code-snippets/outlook-snippets.yaml
- generate-docs/json/office/snippets.yaml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
> [Outlook] (snippet) Remove internetHeaders snippet from MessageRead

- docs/code-snippets/excel-snippets.yaml
- docs/docs-ref-autogen/excel/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_1/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_10/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_2/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_3/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_4/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_5/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_6/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_7/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_8/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_9/excel/excel.range.yml
- docs/docs-ref-autogen/excel_online/excel/excel.range.yml
- generate-docs/json/excel/snippets.yaml
- generate-docs/json/excel_1_1/snippets.yaml
- generate-docs/json/excel_1_10/snippets.yaml
- generate-docs/json/excel_1_2/snippets.yaml
- generate-docs/json/excel_1_3/snippets.yaml
- generate-docs/json/excel_1_4/snippets.yaml
- generate-docs/json/excel_1_5/snippets.yaml
- generate-docs/json/excel_1_6/snippets.yaml
- generate-docs/json/excel_1_7/snippets.yaml
- generate-docs/json/excel_1_8/snippets.yaml
- generate-docs/json/excel_1_9/snippets.yaml
- generate-docs/json/excel_online/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
> Fixing Range.getOffsetRange sample issue

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook/outlook/office.appointmentread.yml
- docs/docs-ref-autogen/outlook/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook/outlook/office.messageread.yml
- docs/docs-ref-autogen/outlook_1_8/outlook/office.appointmentcompose.yml
- docs/docs-ref-autogen/outlook_1_8/outlook/office.appointmentread.yml
- docs/docs-ref-autogen/outlook_1_8/outlook/office.messagecompose.yml
- docs/docs-ref-autogen/outlook_1_8/outlook/office.messageread.yml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Copy snippets from Office.Item to each mode.
> [Outlook] (snippets) getAttachmentContentAsync, getSharedPropertiesAsync

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_1/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_2/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_3/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_4/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_5/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_6/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_7/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_8/outlook/office.customproperties.yml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Related to issue https://github.com/OfficeDev/office-js/issues/914.
> [Outlook] (custom properties) Update saveAsync example

- generate-docs/tools/whats-new.ts
This corrects the Outlook block to the right internal label. It also removes an unnecessary import.
> Minor whats-new tool fixes

- docs/docs-ref-autogen/excel/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_10/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_7/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_8/excel/excel.range.yml
- docs/docs-ref-autogen/excel_1_9/excel/excel.range.yml
- docs/docs-ref-autogen/excel_online/excel/excel.range.yml
- docs/docs-ref-autogen/word/word/word.body.yml
- docs/docs-ref-autogen/word/word/word.paragraph.yml
- docs/docs-ref-autogen/word_1_1/word/word.body.yml
- docs/docs-ref-autogen/word_1_1/word/word.paragraph.yml
- docs/docs-ref-autogen/word_1_2/word/word.body.yml
- docs/docs-ref-autogen/word_1_2/word/word.paragraph.yml
- docs/docs-ref-autogen/word_1_3/word/word.body.yml
- docs/docs-ref-autogen/word_1_3/word/word.paragraph.yml
- generate-docs/api-extractor-inputs-excel-release/Excel_1_10/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_1_7/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_1_8/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_1_9/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_online/excel.d.ts
- generate-docs/api-extractor-inputs-excel/excel.d.ts
- generate-docs/json/snippets.yaml
- generate-docs/json/word/snippets.yaml
- generate-docs/json/word_1_1/snippets.yaml
- generate-docs/json/word_1_2/snippets.yaml
- generate-docs/json/word_1_3/snippets.yaml
- generate-docs/script-inputs/office.d.ts
- generate-docs/script-inputs/office_preview.d.ts
- generate-docs/script-inputs/script-lab-snippets.yaml
Fixes #631 by noting the issue.
> Applying Range issue note from DefinitelyTyped

- docs/docs-ref-autogen/office/office/officeextension.eventhandlers.yml
- generate-docs/api-extractor-inputs-office/office.d.ts
- generate-docs/json/office/office.api.json
- generate-docs/script-inputs/office.d.ts
- generate-docs/script-inputs/office_preview.d.ts
> Adding event handler descriptions

- docs/docs-ref-autogen/word/word/word.selectionmode.yml
- docs/docs-ref-autogen/word_1_1/word/word.selectionmode.yml
- docs/docs-ref-autogen/word_1_2/word/word.selectionmode.yml
- docs/docs-ref-autogen/word_1_3/word/word.selectionmode.yml
- generate-docs/api-extractor-inputs-word-release/word_1_1/word.d.ts
- generate-docs/api-extractor-inputs-word-release/word_1_2/word.d.ts
- generate-docs/api-extractor-inputs-word-release/word_1_3/word.d.ts
- generate-docs/api-extractor-inputs-word/word.d.ts
- generate-docs/json/word/word.api.json
- generate-docs/json/word_1_1/word.api.json
- generate-docs/json/word_1_2/word.api.json
- generate-docs/json/word_1_3/word.api.json
- generate-docs/script-inputs/office.d.ts
- generate-docs/script-inputs/office_preview.d.ts
> Updating with Word enum descriptions from DefintelyTyped

- generate-docs/scripts/midprocessor.ts
There are some repeated code blocks in the midprocessor that work better as a shared function.
> Refactor midprocessor's JSON cleanup

- generate-docs/scripts/midprocessor.ts
> [admin] merge to live!

- docs/docs-ref-autogen/excel/excel/excel.cultureinfo.yml
- docs/docs-ref-autogen/excel/excel/excel.range.yml
- generate-docs/json/excel/snippets.yaml
- generate-docs/json/excel_1_1/snippets.yaml
- generate-docs/json/excel_1_10/snippets.yaml
- generate-docs/json/excel_1_11/snippets.yaml
- generate-docs/json/excel_1_2/snippets.yaml
- generate-docs/json/excel_1_3/snippets.yaml
- generate-docs/json/excel_1_4/snippets.yaml
- generate-docs/json/excel_1_5/snippets.yaml
- generate-docs/json/excel_1_6/snippets.yaml
- generate-docs/json/excel_1_7/snippets.yaml
- generate-docs/json/excel_1_8/snippets.yaml
- generate-docs/json/excel_1_9/snippets.yaml
- generate-docs/json/excel_online/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/script-lab-snippets.yaml
These are the snippets recently authored by @alison-mk in the https://github.com/OfficeDev/office-js-snippets repo.
> Adding latest code samples from office-js-snippets

- docs/code-snippets/excel-snippets.yaml
- docs/docs-ref-autogen/excel/excel/excel.chartaxistitle.yml
- docs/docs-ref-autogen/excel_online/excel/excel.chartaxistitle.yml
- generate-docs/json/excel/snippets.yaml
- generate-docs/json/excel_1_1/snippets.yaml
- generate-docs/json/excel_1_10/snippets.yaml
- generate-docs/json/excel_1_11/snippets.yaml
- generate-docs/json/excel_1_2/snippets.yaml
- generate-docs/json/excel_1_3/snippets.yaml
- generate-docs/json/excel_1_4/snippets.yaml
- generate-docs/json/excel_1_5/snippets.yaml
- generate-docs/json/excel_1_6/snippets.yaml
- generate-docs/json/excel_1_7/snippets.yaml
- generate-docs/json/excel_1_8/snippets.yaml
- generate-docs/json/excel_1_9/snippets.yaml
- generate-docs/json/excel_online/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Adding a small snippet showing how to orient the text of a chart axis label.
> Adding ChartAxisTitle.textOrientation snippet

- generate-docs/scripts/package-lock.json
- generate-docs/scripts/package.json
- generate-docs/tools/package-lock.json
- generate-docs/tools/package.json
- generate-docs/tools/whats-new.ts
This PR also updates the package.json to address security vulnerabilities.
> Update the whats-new tool to support PowerPoint

- docs/docs-ref-autogen/overview/overview.md
Removes a tags from around each "card"
[Sample preview page](https://review.docs.microsoft.com/en-us/javascript/api/overview?branch=elizs-remove-fake-links&view=powerpoint-js-preview)
> [Admin] Clean up fake links

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.notificationmessageaction.yml
- generate-docs/api-extractor-inputs-outlook/outlook.d.ts
- generate-docs/json/outlook/outlook.api.json
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/outlook_1_9/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Related to issue https://github.com/OfficeDev/office-js-docs-reference/issues/838.
> [Outlook] Add example for NotificationMessageAction

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.notificationmessageaction.yml
- generate-docs/api-extractor-inputs-outlook/outlook.d.ts
- generate-docs/json/outlook/outlook.api.json
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/outlook_1_9/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
* [Outlook] Add example for NotificationMessageAction
* Get latest
* Tweak
> [Outlook] Add example for NotificationMessageAction (#886)

- docs/docs-ref-autogen/excel/excel/excel.workbook.yml
- docs/docs-ref-autogen/excel/excel/excel.worksheetcollection.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.presentation.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.slidecollection.yml
- docs/docs-ref-autogen/powerpoint_1_2/powerpoint/powerpoint.presentation.yml
- generate-docs/json/excel/snippets.yaml
- generate-docs/json/excel_1_1/snippets.yaml
- generate-docs/json/excel_1_10/snippets.yaml
- generate-docs/json/excel_1_11/snippets.yaml
- generate-docs/json/excel_1_12/snippets.yaml
- generate-docs/json/excel_1_2/snippets.yaml
- generate-docs/json/excel_1_3/snippets.yaml
- generate-docs/json/excel_1_4/snippets.yaml
- generate-docs/json/excel_1_5/snippets.yaml
- generate-docs/json/excel_1_6/snippets.yaml
- generate-docs/json/excel_1_7/snippets.yaml
- generate-docs/json/excel_1_8/snippets.yaml
- generate-docs/json/excel_1_9/snippets.yaml
- generate-docs/json/excel_online/snippets.yaml
- generate-docs/json/powerpoint/snippets.yaml
- generate-docs/json/powerpoint_1_1/snippets.yaml
- generate-docs/json/powerpoint_1_2/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/script-lab-snippets.yaml
@Rick-Kirkham @alison-mk Please verify your snippets are pulled in correctly.
> [Admin] Get latest changes

- docs/docs-ref-autogen/office/office/office.addin.yml
- docs/docs-ref-autogen/office/office/office.removehandleroptions.yml
- docs/docs-ref-autogen/powerpoint/powerpoint.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.shapecollectionloadoptions.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.shapedata.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.shapeloadoptions.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagcollectiondata.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagcollectionloadoptions.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagcollectionupdatedata.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagdata.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagloadoptions.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagupdatedata.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.presentation.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.shape.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.slide.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.tag.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.tagcollection.yml
- docs/docs-ref-autogen/powerpoint/toc.yml
- docs/requirement-set-tables/powerpoint-preview.md
- generate-docs/api-extractor-inputs-office/office.d.ts
- generate-docs/api-extractor-inputs-powerpoint/powerpoint.d.ts
- generate-docs/json/office/office.api.json
- generate-docs/json/powerpoint/powerpoint.api.json
- generate-docs/script-inputs/office.d.ts
- generate-docs/scripts/preprocessor.ts
This includes new PPT APIs and type changes in Common to remove warnings.
@Rick-Kirkham, FYI, this also updates the PPT preview requirement set table, so you'll be able to make the followup PR in -pr.
> Update with latest from DefinitelyTyped

- docs/docs-ref-autogen/office/office/office.addin.yml
- docs/docs-ref-autogen/office/office/office.removehandleroptions.yml
- docs/docs-ref-autogen/powerpoint/powerpoint.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.shapecollectionloadoptions.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.shapedata.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.shapeloadoptions.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagcollectiondata.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagcollectionloadoptions.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagcollectionupdatedata.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagdata.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagloadoptions.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.tagupdatedata.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.presentation.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.shape.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.slide.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.tag.yml
- docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.tagcollection.yml
- docs/docs-ref-autogen/powerpoint/toc.yml
- docs/requirement-set-tables/powerpoint-preview.md
- generate-docs/api-extractor-inputs-office/office.d.ts
- generate-docs/api-extractor-inputs-powerpoint/powerpoint.d.ts
- generate-docs/json/office/office.api.json
- generate-docs/json/powerpoint/powerpoint.api.json
- generate-docs/script-inputs/office.d.ts
- generate-docs/scripts/preprocessor.ts
* Test export type
* Test export type
* Test type change
* Update with latest from DefinitelyTyped
> Update with latest from DefinitelyTyped (#910)

- docs/docs-ref-autogen/overview/overview.md
* Reordering PPT on index page
* Reordering PPT Overview req sets
> Reorder PPT on the reference overview page (#916)

- docs/docs-ref-autogen/excel/excel/excel.workbook.yml
- generate-docs/json/excel/snippets.yaml
- generate-docs/json/excel_1_1/snippets.yaml
- generate-docs/json/excel_1_10/snippets.yaml
- generate-docs/json/excel_1_11/snippets.yaml
- generate-docs/json/excel_1_12/snippets.yaml
- generate-docs/json/excel_1_2/snippets.yaml
- generate-docs/json/excel_1_3/snippets.yaml
- generate-docs/json/excel_1_4/snippets.yaml
- generate-docs/json/excel_1_5/snippets.yaml
- generate-docs/json/excel_1_6/snippets.yaml
- generate-docs/json/excel_1_7/snippets.yaml
- generate-docs/json/excel_1_8/snippets.yaml
- generate-docs/json/excel_1_9/snippets.yaml
- generate-docs/json/excel_online/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/script-lab-snippets.yaml
@alison-mk In case you want to take a look...
> [Admin] Get latest updates

- docs/docfx.json
* Shifting Office from all to common
* Adding common-js to all but visio
* Allowing for unique common TOC
> [monikers] Decouple the Common APIs from Visio (#978)

- docs/docs-ref-autogen/excel/custom-functions-runtime/customfunctions.invocation.yml
- docs/docs-ref-autogen/excel_1_10/custom-functions-runtime/customfunctions.invocation.yml
- docs/docs-ref-autogen/excel_1_11/custom-functions-runtime/customfunctions.invocation.yml
- docs/docs-ref-autogen/excel_1_12/custom-functions-runtime/customfunctions.invocation.yml
- docs/docs-ref-autogen/excel_1_13/custom-functions-runtime/customfunctions.invocation.yml
- docs/docs-ref-autogen/excel_1_9/custom-functions-runtime/customfunctions.invocation.yml
- docs/docs-ref-autogen/excel_online/custom-functions-runtime/customfunctions.invocation.yml
- generate-docs/api-extractor-inputs-custom-functions-runtime/custom-functions-runtime.d.ts
- generate-docs/json/custom-functions-runtime.api.json
- generate-docs/json/excel/custom-functions-runtime.api.json
- generate-docs/json/excel_1_10/custom-functions-runtime.api.json
- generate-docs/json/excel_1_11/custom-functions-runtime.api.json
- generate-docs/json/excel_1_12/custom-functions-runtime.api.json
- generate-docs/json/excel_1_13/custom-functions-runtime.api.json
- generate-docs/json/excel_1_9/custom-functions-runtime.api.json
- generate-docs/json/excel_online/custom-functions-runtime.api.json
- generate-docs/script-inputs/custom-functions-runtime.d.ts
- generate-docs/tools/API Coverage Report.csv
* [admin] Get latest changes
* include yaml changes
> [admin] Publish

- docs/docs-ref-autogen/excel/excel/excel.interfaces.pivotfielddata.yml
- docs/docs-ref-autogen/excel/excel/excel.pivotfield.yml
- docs/docs-ref-autogen/excel_1_10/excel/excel.interfaces.pivotfielddata.yml
- docs/docs-ref-autogen/excel_1_10/excel/excel.pivotfield.yml
- docs/docs-ref-autogen/excel_1_11/excel/excel.interfaces.pivotfielddata.yml
- docs/docs-ref-autogen/excel_1_11/excel/excel.pivotfield.yml
- docs/docs-ref-autogen/excel_1_12/excel/excel.interfaces.pivotfielddata.yml
- docs/docs-ref-autogen/excel_1_12/excel/excel.pivotfield.yml
- docs/docs-ref-autogen/excel_1_13/excel/excel.interfaces.pivotfielddata.yml
- docs/docs-ref-autogen/excel_1_13/excel/excel.pivotfield.yml
- docs/docs-ref-autogen/excel_1_8/excel/excel.interfaces.pivotfielddata.yml
- docs/docs-ref-autogen/excel_1_8/excel/excel.pivotfield.yml
- docs/docs-ref-autogen/excel_1_9/excel/excel.interfaces.pivotfielddata.yml
- docs/docs-ref-autogen/excel_1_9/excel/excel.pivotfield.yml
- docs/docs-ref-autogen/excel_online/excel/excel.interfaces.pivotfielddata.yml
- docs/docs-ref-autogen/excel_online/excel/excel.pivotfield.yml
- docs/requirement-set-tables/excel-1_8.md
- generate-docs/api-extractor-inputs-excel-release/Excel_1_10/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_1_11/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_1_12/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_1_13/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_1_8/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_1_9/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_online/excel.d.ts
- generate-docs/api-extractor-inputs-excel/excel.d.ts
- generate-docs/script-inputs/office.d.ts
@alison-mk In case you want to take a look
> [all hosts] Get latest changes

- docs/docs-ref-autogen/office/office-runtime/officeruntime.storage.yml
- generate-docs/api-extractor-inputs-office-runtime/office-runtime.d.ts
- generate-docs/json/office-runtime.api.json
- generate-docs/json/office/office-runtime.api.json
- generate-docs/script-inputs/office-runtime.d.ts
- generate-docs/tools/API Coverage Report.csv
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56978
> [Outlook] (office-runtime) Mailbox 1.10 supports Storage

- docs/docs-ref-autogen/office/office/office.document.yml
- docs/docs-ref-autogen/office/office/office.eventtype.yml
- docs/docs-ref-autogen/office_release/office/office.document.yml
- docs/docs-ref-autogen/office_release/office/office.eventtype.yml
- generate-docs/api-extractor-inputs-office-release/office.d.ts
- generate-docs/api-extractor-inputs-office/office.d.ts
- generate-docs/json/office/office.api.json
- generate-docs/json/office_release/office.api.json
- generate-docs/tools/API Coverage Report.csv
> [all hosts] Get latest updates

- docs/docs-ref-autogen/excel/excel/excel.range.yml
- docs/docs-ref-autogen/office/office/office.error.yml
- docs/docs-ref-autogen/office_release/office/office.error.yml
- generate-docs/api-extractor-inputs-office-release/office.d.ts
- generate-docs/api-extractor-inputs-office/office.d.ts
- generate-docs/json/excel/snippets.yaml
- generate-docs/json/excel_1_1/snippets.yaml
- generate-docs/json/excel_1_10/snippets.yaml
- generate-docs/json/excel_1_11/snippets.yaml
- generate-docs/json/excel_1_12/snippets.yaml
- generate-docs/json/excel_1_13/snippets.yaml
- generate-docs/json/excel_1_14/snippets.yaml
- generate-docs/json/excel_1_2/snippets.yaml
- generate-docs/json/excel_1_3/snippets.yaml
- generate-docs/json/excel_1_4/snippets.yaml
- generate-docs/json/excel_1_5/snippets.yaml
- generate-docs/json/excel_1_6/snippets.yaml
- generate-docs/json/excel_1_7/snippets.yaml
- generate-docs/json/excel_1_8/snippets.yaml
- generate-docs/json/excel_1_9/snippets.yaml
- generate-docs/json/excel_online/snippets.yaml
- generate-docs/json/office/office.api.json
- generate-docs/json/office_release/office.api.json
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/script-lab-snippets.yaml
- generate-docs/tools/API Coverage Report.csv
FYI @alison-mk for Excel changes and @AlexJerabek for Common changes
> [all hosts] Get latest

- docs/docs-ref-autogen/office/office/office.actions.yml
- docs/docs-ref-autogen/office/office/office.officetheme.yml
- docs/docs-ref-autogen/office/office/officeextension.debuginfo.yml
- docs/docs-ref-autogen/office_release/office/office.actions.yml
- docs/docs-ref-autogen/office_release/office/office.officetheme.yml
- docs/docs-ref-autogen/office_release/office/officeextension.debuginfo.yml
- generate-docs/api-extractor-inputs-office-release/office.d.ts
- generate-docs/api-extractor-inputs-office/office.d.ts
- generate-docs/json/office/office.api.json
- generate-docs/json/office_release/office.api.json
- generate-docs/tools/API Coverage Report.csv
> [Common] Getting latest from DefinitelyTyped

- docs/docfx.json
https://portal.microsofticm.com/imp/v3/incidents/details/309205435/home
> try fixing TOC

- docs/docfx.json
Per comment in https://portal.microsofticm.com/imp/v3/incidents/details/309205435/home, we still have a minor TOC issue. Thus, let's try another way of the whole fix to see whether this can fix both problems.
> try fixing a 2nd toc issue

- docs/includes/using-preview-apis-host.md
Fixes #1275.
This also gets the latest from DefinitelyTyped.
> [all hosts] (requirement-sets) Update preview @types instructions

- docs/manifest/id.md
Fixes a verbatim from a customer.
> [All Hosts] (manifest) how to get add-in ID

- docs/manifest/form.md
> [Outlook] (manifest) Add Form element attributes

- docs/manifest/customfunctionssourcelocation.md
- docs/manifest/extensionpoint.md
- docs/manifest/sourcelocation.md
- docs/manifest/toc.yml
Related to PR https://github.com/OfficeDev/office-js-docs-pr/pull/3491.
> [all hosts] (manifest) SourceLocation clarifications

- docs/code-snippets/excel-snippets.yaml
[Internal tracking item](https://office.visualstudio.com/OC/_workitems/edit/5864127).
> [Excel] (Query) Add Query and QueryCollection snippets

- docs/requirement-sets/powerpoint/powerpoint-api-requirement-sets.md
> [All hosts] Fix broken links

- docs/requirement-sets/common/shared-runtime-requirement-sets.md
This adds build information for the GA of shared runtime for Word and PowerPoint.
> [Word and PowerPoint](shared runtime) update requirement sets

- docs/manifest/appdomain.md
> [All Hosts] (manifest) AppDomain protocol restriction

- docs/requirement-sets/outlook/outlook-api-requirement-sets.md
Divide the opening passage into separate tabs for the XML and JSON manifests.
> [Outlook] (manifest) how to use req set in JSON manifest

- docs/manifest/functionfile.md
> [All hosts] (manifest) Add link to Resources element from FunctionFile page

- docs/docs-ref-autogen/overview/overview.md
This section seems less important than the application selection. Most people going here need to be routed to a specific set of application APIs, so we should optimize for that.
> [all hosts] (Overview) Move special req set section lower

- docs/docs-ref-autogen/excel/excel/excel.entitycompactlayouticons.yml
- docs/docs-ref-autogen/excel_1_16/excel/excel.entitycompactlayouticons.yml
- docs/docs-ref-autogen/excel_online/excel/excel.entitycompactlayouticons.yml
- generate-docs/api-extractor-inputs-excel-release/Excel_1_16/excel.d.ts
- generate-docs/api-extractor-inputs-excel-release/Excel_online/excel.d.ts
- generate-docs/api-extractor-inputs-excel/excel.d.ts
- generate-docs/scripts/preprocessor.ts
- generate-docs/tools/API Coverage Report.csv
This allows the preprocessor to correctly handle enum members named after reserved keywords.
> [scripts] (Preprocessor) Improving regexes for exporting declarations

- docs/requirement-sets/excel/custom-functions-requirement-sets.md
Version information gathered from: 
https://github.com/OfficeDev/Office-Js-Requirement-Sets/pull/109
https://learn.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date
> [Excel] (Custom functions) Update requirement set table

- docs/manifest/officetab.md
[Internal work item](https://office.visualstudio.com/OC/_workitems/edit/7072319).
@AlexJerabek I've never made updates to the manifest directory in this repo, lmk if I need to take any additional steps.
> [All hosts] Update OfficeTab element in the manifest article

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_1/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_10/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_11/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_12/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_2/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_3/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_4/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_5/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_6/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_7/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_8/outlook/office.customproperties.yml
- docs/docs-ref-autogen/outlook_1_9/outlook/office.customproperties.yml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_10/snippets.yaml
- generate-docs/json/outlook_1_11/snippets.yaml
- generate-docs/json/outlook_1_12/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/outlook_1_9/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Related PRs: 
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63630
- https://github.com/OfficeDev/office-js-docs-pr/pull/3778
> [Outlook] (CustomProperties) Correct custom properties description in code snippet

- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/3785
> [Outlook] (preview) Add entry for the OnMessageFromChanged event

- docs/manifest/extendedpermission.md
- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Adds the prepend-on-send feature to the preview and ExtendedPermission pages.
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63875
> [Outlook] (preview) Add prepend-on-send feature

- docs/code-snippets/office-snippets.yaml
- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/office/office/office.context.yml
- docs/docs-ref-autogen/outlook/outlook/office.sensitivitylabeldetails.yml
- generate-docs/json/office/snippets.yaml
- generate-docs/json/office_release/snippets.yaml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_10/snippets.yaml
- generate-docs/json/outlook_1_11/snippets.yaml
- generate-docs/json/outlook_1_12/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/outlook_1_9/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/tools/API Coverage Report.csv
Adds code samples to `Office.context.sensitivityLabelsCatalog` and `Office.SensitivityLabelDetails`.
> [Outlook] (sensitivity label) Add code samples to API

- docs/code-snippets/office-snippets.yaml
- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/office/office/office.context.yml
- docs/docs-ref-autogen/outlook/outlook/office.sensitivitylabeldetails.yml
- docs/requirement-sets/outlook/preview-requirement-set/office.context.mailbox.item.md
- docs/requirement-sets/outlook/preview-requirement-set/office.context.md
- docs/requirement-sets/outlook/preview-requirement-set/office.md
- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
- generate-docs/json/office/snippets.yaml
- generate-docs/json/office_release/snippets.yaml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_10/snippets.yaml
- generate-docs/json/outlook_1_11/snippets.yaml
- generate-docs/json/outlook_1_12/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/outlook_1_9/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/tools/API Coverage Report.csv
A fix is being rolled out to the sensitivity label codebase. Until then, we'll have to remove the sensitivity label API from our reference docs.
Internal work item: 7539773
> [Outlook] (sensitivity label) Remove sensitivity label API from preview

- docs/manifest/extensionpoint.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/3834
> [Outlook] (CRM) Add Outlook on iOS support

- docs/requirement-sets/outlook/preview-requirement-set/office.context.mailbox.item.md
- docs/requirement-sets/outlook/preview-requirement-set/office.context.md
- docs/requirement-sets/outlook/preview-requirement-set/office.md
- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64511
> [Outlook] (sensitivity label) Republish sensitivity label API (preview)

- docs/code-snippets/office-snippets.yaml
- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/office/office/office.context.yml
- docs/docs-ref-autogen/outlook/outlook/office.sensitivitylabeldetails.yml
- generate-docs/json/office/snippets.yaml
- generate-docs/json/office_release/snippets.yaml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_10/snippets.yaml
- generate-docs/json/outlook_1_11/snippets.yaml
- generate-docs/json/outlook_1_12/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/outlook_1_9/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/tools/API Coverage Report.csv
Adds code samples to Context.sensitivityLabelsCatalog and SensitivityLabelDetails.
> [Outlook] (sensitivity label) Add code samples

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.delaydeliverytime.yml
- docs/docs-ref-autogen/outlook/outlook/office.messagecompose.yml
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_10/snippets.yaml
- generate-docs/json/outlook_1_11/snippets.yaml
- generate-docs/json/outlook_1_12/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/outlook_1_9/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/tools/API Coverage Report.csv
Script Lab snippets are mapped in https://github.com/OfficeDev/office-js-snippets/pull/774.
> [Outlook] (DelayDeliveryTime) Remove samples that will be replaced by Script Lab snippets

- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/3950
> [Outlook] (sensitivity label) Clarify Microsoft 365 license requirement

- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/3949
> [Outlook] (FromChanged events) Add Outlook on Mac support

- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/3956
> [Outlook] (prepend-on-send) Add Outlook on Mac support

- docs/requirement-sets/outlook/preview-requirement-set/office.context.mailbox.item.md
- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65200
> [Outlook] (preview) Added the closeAsync API

- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Applies suggestion from review to update the `getSelectedItemsAsync` method link.
> [Outlook] (multi-select) Update link

- docs/code-snippets/office-snippets.yaml
- docs/docs-ref-autogen/office/office/office.addincommands.eventcompletedoptions.yml
- generate-docs/json/office/snippets.yaml
- generate-docs/json/office_release/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/tools/API Coverage Report.csv
Adds code snippets to the `event.completed` options applicable to the integrated spam reporting feature.
> [Outlook] (spam reporting) Add code snippets to event.completed options

- docs/manifest/officetab.md
Fixes [1646](https://github.com/OfficeDev/office-js-docs-reference/issues/1646)
> [All Hosts] (manifest) Correct 2 errors in OfficeTab reference

- docs/code-snippets/office-snippets.yaml
- docs/code-snippets/outlook-snippets.yaml
- docs/manifest/functionfile.md
- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
- docs/requirement-sets/outlook/requirement-set-1.10/outlook-requirement-set-1.10.md
- docs/requirement-sets/outlook/requirement-set-1.12/outlook-requirement-set-1.12.md
Related PRs:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66485
- https://github.com/OfficeDev/office-js-docs-pr/pull/4150
- https://github.com/OfficeDev/Office-Add-in-samples/pull/584
> [Outlook] (event) Remap snippets and update links

- docs/docfx.json
Seems like sending users to M365 product is too broad.
> [all hosts] Refine product feedback link

- docs/requirement-sets/outlook/preview-requirement-set/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.10/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.11/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.12/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.13/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.3/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.3/outlook-requirement-set-1.3.md
- docs/requirement-sets/outlook/requirement-set-1.4/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.5/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.6/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.7/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.8/office.context.mailbox.md
- docs/requirement-sets/outlook/requirement-set-1.9/office.context.mailbox.md
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67009
> [Outlook] (EWS and REST) Update convertToEwsId and convertToRestId parameter

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.mailboxenums.actiontype.yml
- docs/docs-ref-autogen/outlook/outlook/office.notificationmessageaction.yml
- docs/docs-ref-autogen/outlook_1_10/outlook/office.mailboxenums.actiontype.yml
- docs/docs-ref-autogen/outlook_1_10/outlook/office.notificationmessageaction.yml
- docs/docs-ref-autogen/outlook_1_11/outlook/office.mailboxenums.actiontype.yml
- docs/docs-ref-autogen/outlook_1_11/outlook/office.notificationmessageaction.yml
- docs/docs-ref-autogen/outlook_1_12/outlook/office.mailboxenums.actiontype.yml
- docs/docs-ref-autogen/outlook_1_12/outlook/office.notificationmessageaction.yml
- docs/docs-ref-autogen/outlook_1_13/outlook/office.mailboxenums.actiontype.yml
- docs/docs-ref-autogen/outlook_1_13/outlook/office.notificationmessageaction.yml
- generate-docs/API Coverage Report.csv
- generate-docs/json/outlook/snippets.yaml
- generate-docs/json/outlook_1_1/snippets.yaml
- generate-docs/json/outlook_1_10/snippets.yaml
- generate-docs/json/outlook_1_11/snippets.yaml
- generate-docs/json/outlook_1_12/snippets.yaml
- generate-docs/json/outlook_1_13/snippets.yaml
- generate-docs/json/outlook_1_2/snippets.yaml
- generate-docs/json/outlook_1_3/snippets.yaml
- generate-docs/json/outlook_1_4/snippets.yaml
- generate-docs/json/outlook_1_5/snippets.yaml
- generate-docs/json/outlook_1_6/snippets.yaml
- generate-docs/json/outlook_1_7/snippets.yaml
- generate-docs/json/outlook_1_8/snippets.yaml
- generate-docs/json/outlook_1_9/snippets.yaml
- generate-docs/json/snippets.yaml
- generate-docs/script-inputs/local-repo-snippets.yaml
Related PR: https://github.com/OfficeDev/office-js-snippets/pull/826
> [Outlook] (notifications) Replace code samples with Script Lab snippets

- docs/manifest/action.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4220
> [Outlook] (contextless) Clarify feature support in Outlook on the web

- docs/manifest/event.md
- docs/manifest/extensionpoint.md
- docs/manifest/launchevent.md
- docs/requirement-sets/outlook/requirement-set-1.12/outlook-requirement-set-1.12.md
Updates links after reorganizing Smart Alerts documentation (see https://github.com/OfficeDev/office-js-docs-pr/pull/4217).
> [Outlook] (Smart Alerts) Update links

- docs/manifest/sourcelocation.md
Requested in November 2023 verbatim.
> [All Hosts] (manifest) guidance for source location

- docs/code-snippets/excel-snippets.yaml
- docs/docs-ref-autogen/excel/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_1/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_10/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_11/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_12/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_13/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_14/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_15/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_16/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_17/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_2/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_3/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_4/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_5/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_6/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_7/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_8/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_1_9/excel/excel.worksheet.yml
- docs/docs-ref-autogen/excel_online/excel/excel.worksheet.yml
- generate-docs/API Coverage Report.csv
- generate-docs/script-inputs/local-repo-snippets.yaml
> [excel] (Worksheet) Add Worksheet.set sample

- docs/code-snippets/word-snippets.yaml
- docs/docs-ref-autogen/word/word/word.range.yml
- docs/docs-ref-autogen/word_1_3/word/word.range.yml
- docs/docs-ref-autogen/word_1_3_hidden_document/word/word.range.yml
- docs/docs-ref-autogen/word_1_4/word/word.range.yml
- docs/docs-ref-autogen/word_1_4_hidden_document/word/word.range.yml
- docs/docs-ref-autogen/word_1_5/word/word.range.yml
- docs/docs-ref-autogen/word_1_5_hidden_document/word/word.range.yml
- docs/docs-ref-autogen/word_1_6/word/word.range.yml
- docs/docs-ref-autogen/word_online/word/word.range.yml
- generate-docs/API Coverage Report.csv
- generate-docs/script-inputs/local-repo-snippets.yaml
> [word] (Hyperlinks) Add Word.Range.getHyperlinkRanges sample

- docs/requirement-sets/outlook/preview-requirement-set/office.context.md
- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68162
> [Outlook] (preview) Add runtime URL property

- docs/code-snippets/office-snippets.yaml
This PR changes the jQuery event commands to use the modern syntax.
> [all-hosts] (UX) Change samples to use the current jQuery onclick syntax

- docs/requirement-sets/common/add-in-commands-requirement-sets.md
Related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/4393
> [all hosts] Specify which clients support AddinCommmands 1.3

- docs/code-snippets/office-snippets.yaml
- docs/docs-ref-autogen/office/office/office.document.yml
- docs/docs-ref-autogen/office_release/office/office.document.yml
- generate-docs/API Coverage Report.csv
- generate-docs/script-inputs/local-repo-snippets.yaml
Office.Document is one of the more highly trafficked pages. This small snippet shows how to access the object and should make the object model clearer.
> [common] (Document) Adding a class-level Office.Document snippet

- docs/code-snippets/office-snippets.yaml
- docs/docs-ref-autogen/office/office/office.asynccontextoptions.yml
- docs/docs-ref-autogen/office/office/office.ui.yml
- docs/docs-ref-autogen/office_release/office/office.asynccontextoptions.yml
- docs/docs-ref-autogen/office_release/office/office.ui.yml
- generate-docs/API Coverage Report.csv
- generate-docs/script-inputs/local-repo-snippets.yaml
- generate-docs/script-inputs/script-lab-snippets.yaml
Adds code samples to Office.UI.addHandlerAsync and Office.AsyncContextOptions.
> [All hosts] (code samples) Add code samples

- docs/requirement-sets/common/ribbon-api-requirement-sets.md
Fixes https://github.com/OfficeDev/office-js-docs-reference/issues/1823
> [all hosts] (RibbonApi) Correct details

- docs/manifest/officemenu.md
Doesn't need a review.
Fixes [1860](https://github.com/OfficeDev/office-js-docs-reference/issues/1860)
> [All Hosts] (manifest) correct OfficeMenu attribute name

- docs/code-snippets/office-snippets.yaml
- docs/docs-ref-autogen/office/office/office.asyncresult.yml
- docs/docs-ref-autogen/office/office/office.asyncresultstatus.yml
- docs/docs-ref-autogen/office/office/office.document.yml
- docs/docs-ref-autogen/office_release/office/office.asyncresult.yml
- docs/docs-ref-autogen/office_release/office/office.asyncresultstatus.yml
- docs/docs-ref-autogen/office_release/office/office.document.yml
- generate-docs/script-inputs/local-repo-snippets.yaml
- Updates some samples to use enums where possible.
- Updates JS code syntax since samples were already being updated. Other samples will be addressed in a separate PR.
> [All hosts] (sample) Update samples to use enums

- docs/docs-ref-autogen/overview/overview.md
FYI: [HTML FAQ](https://review.learn.microsoft.com/en-us/help/platform/html-faq?branch=main#i-rely-on-html-for-some-functionality-that-isnt-supported-in-markdown-will-it-remain-available)
> [all hosts] Remove disallowed HTML

- docs/code-snippets/excel-snippets.yaml
- docs/docs-ref-autogen/excel/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_1/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_10/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_11/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_12/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_13/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_14/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_15/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_16/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_17/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_2/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_3/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_4/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_5/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_6/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_7/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_8/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_1_9/excel/excel.rangefont.yml
- docs/docs-ref-autogen/excel_online/excel/excel.rangefont.yml
- generate-docs/API Coverage Report.csv
- generate-docs/script-inputs/local-repo-snippets.yaml
> [excel] (Range) Add a sample for changing the range font

- docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Related PRs:
- https://github.com/OfficeDev/office-js-docs-pr/pull/4474
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69054
> [Outlook] (spam reporting) Document support on other platforms

- docs/manifest/iconurl.md
Based on customer feedback that it was unclear SVG icons were not supported.
> [all] (Manifest) Make supported icon file types more clear

- docs/code-snippets/office-snippets.yaml
- docs/docs-ref-autogen/office/office/office.context.yml
- docs/docs-ref-autogen/office/office/office.officetheme.yml
- docs/docs-ref-autogen/office_release/office/office.context.yml
- docs/docs-ref-autogen/office_release/office/office.officetheme.yml
- generate-docs/script-inputs/local-repo-snippets.yaml
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69663
> [All hosts] (OfficeTheme) Update code samples

- docs/code-snippets/office-snippets.yaml
- docs/docs-ref-autogen/office/office/office.context.yml
- docs/docs-ref-autogen/office/office/office.officetheme.yml
- docs/docs-ref-autogen/office/office/office.themeid.yml
- docs/docs-ref-autogen/office_release/office/office.context.yml
- docs/docs-ref-autogen/office_release/office/office.officetheme.yml
- docs/docs-ref-autogen/office_release/office/office.themeid.yml
- generate-docs/API Coverage Report.csv
- generate-docs/script-inputs/local-repo-snippets.yaml
- Maps a code snippet to the Office.ThemeId enum page.
- Corrects existing OfficeTheme code snippets.
> [All hosts] (OfficeTheme) Add code snippet to Office.ThemeId enum

- docs/code-snippets/office-snippets.yaml
- docs/docs-ref-autogen/office/office/office.devicepermission.yml
- docs/docs-ref-autogen/office/office/office.devicepermissiontype.yml
- docs/docs-ref-autogen/office_release/office/office.devicepermission.yml
- docs/docs-ref-autogen/office_release/office/office.devicepermissiontype.yml
- generate-docs/script-inputs/local-repo-snippets.yaml
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69854
> [All hosts] (DevicePermission) Update code samples

- docs/code-snippets/office-snippets.yaml
- docs/docs-ref-autogen/office/office/office.ribbon.yml
- docs/docs-ref-autogen/office_release/office/office.ribbon.yml
- generate-docs/API Coverage Report.csv
- generate-docs/script-inputs/local-repo-snippets.yaml
Add code snippet to the `requestCreateControls` method.
> [Excel] (RibbonApi) Add code snippet

- Contributing.md
Matching some of the edits in this PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4730
> [admin] (Contributor) Minor edits to contributor file

- docs/manifest/extensionpoint.md
- docs/manifest/officemenu.md
Fixes [2023](https://github.com/OfficeDev/office-js-docs-reference/issues/2023)
> [All Hosts] (manifest) correct attribute of OfficeMenu element

- docs/code-snippets/office-snippets.yaml
- generate-docs/API Coverage Report.csv
- generate-docs/script-inputs/local-repo-snippets.yaml
Adds code samples to `closeContainer` and `openBrowserWindow`.
> [All hosts] (UI) Add code samples

- docs/code-snippets/office-snippets.yaml
- docs/manifest/toc.yml
Technical fixes that don't need a review.
> [All Hosts] (toc, samples) TOC fix and fix categories for samples

- docs/manifest/rule.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4770
> [Outlook] (manifest) Move information from conceptual article

- generate-docs/scripts/preprocessor.ts
Also taking the opportunity to clean up the CDN option
> [Admin] (preprocessor) Handle Local option

- docs/code-snippets/office-snippets.yaml
- docs/code-snippets/officeruntime-snippets.yaml
- docs/code-snippets/outlook-snippets.yaml
For the OfficeRuntime.Auth interface, I created a new file officeruntime-snippets.yaml on the pattern of the other files. I assume that's all that's needed.
> [All Hosts] (snippets) Adding some high-value snippets

- docs/code-snippets/outlook-snippets.yaml
- docs/docs-ref-autogen/outlook/outlook/office.mailbox.yml
- docs/docs-ref-autogen/outlook_1_10/outlook/office.mailbox.yml
- docs/docs-ref-autogen/outlook_1_11/outlook/office.mailbox.yml
- docs/docs-ref-autogen/outlook_1_12/outlook/office.mailbox.yml
- docs/docs-ref-autogen/outlook_1_13/outlook/office.mailbox.yml
- docs/docs-ref-autogen/outlook_1_14/outlook/office.mailbox.yml
- docs/docs-ref-autogen/outlook_1_5/outlook/office.mailbox.yml
- docs/docs-ref-autogen/outlook_1_6/outlook/office.mailbox.yml
- docs/docs-ref-autogen/outlook_1_7/outlook/office.mailbox.yml
- docs/docs-ref-autogen/outlook_1_8/outlook/office.mailbox.yml
- docs/docs-ref-autogen/outlook_1_9/outlook/office.mailbox.yml
- generate-docs/script-inputs/local-repo-snippets.yaml
Related PR: https://github.com/OfficeDev/office-js-snippets/pull/943
> [Outlook] (code sample) Add snippet to restUrl property

- docs/requirement-sets/common/nested-app-auth-requirement-sets.md
NAA is now GA for monthly enterprise channel.
> [All hosts](NAA) update GA date for monthly enterprise channel

- docs/requirement-sets/common/keyboard-shortcuts-requirement-sets.md
Related to https://github.com/OfficeDev/Office-Add-in-samples/pull/897.
> [Word] (keyboard shortcuts) Clarify feature support in Word on the web

- docs/docs-ref-autogen/excel/excel/excel.cellpropertiesloadoptions.yml
- docs/docs-ref-autogen/excel/excel/excel.notecollection.yml
- docs/docs-ref-autogen/excel/excel/excel.settablecellproperties.yml
- docs/includes/excel-preview.md
- generate-docs/api-extractor-inputs-excel/excel.d.ts
Making sure the latest updates all still publish correctly. Might as well follow through with the process instead of waiting until next week.
> Getting latest from DefinitelyTyped

- docs/requirement-sets/word/word-api-1-7-requirement-set.md
Related to https://github.com/OfficeDev/office-js/issues/4953
> [Word] (Annotations) Note M365 subscription requirement

- docs/docfx.json
Aligning with new Learn standards.
> [admin] (metadata) Change autogened pages to generated-reference ms.topic

- docs/manifest/extendedoverrides.md
- docs/manifest/override.md
- docs/manifest/token.md
- docs/manifest/tokens.md
Related to https://github.com/OfficeDev/office-js-docs-pr/pull/4678. Updates link to deleted article.
> [Excel/Word] Update links to deleted article

- docs/manifest/commandsurface.md
- docs/manifest/customfunctionssourcelocation.md
- docs/manifest/extensionpoint.md
- docs/manifest/toc.yml
Fixes #2208.
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/5071
> [Outlook] (manifest) Fix Module extension point documentation

- docs/manifest/action.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/5075
> [All hosts] (add-in commands) Add information about the Office.actions.associate call

- docs/manifest/desktopsettings.md
Related to https://github.com/OfficeDev/Office-Add-in-samples/issues/941.
> [Outlook] (manifest) Document child elements of DesktopSettings element

- docs/manifest/versionoverrides-1-0-mail.md
- docs/manifest/versionoverrides-1-0-taskpane.md
- docs/manifest/versionoverrides-1-1-mail.md
Purely technical fix that doesn't need a review.
> [All Hosts] (manifest) remove erroneous requirement

- docs/manifest/customtab.md
Fixes https://github.com/OfficeDev/office-js-docs-reference/issues/2289.
> [UI/UX] (custom tab) Fix attribute value in code samples

- docs/code-snippets/outlook-snippets.yaml
An internal person reported a pair of typos in this sample. This PR applies the corrections.
> [outlook] (Events) Fix EnhancedLocation sample typo

- docs/requirement-sets/outlook/outlook-api-requirement-sets.md
Fixes https://github.com/OfficeDev/office-js-docs-reference/issues/2293.
> [Outlook] Document requirement set support for Exchange Server SE
