docs/docs-ref-conceptual/overview/excel-add-ins-reference-overview.md, docs/docs-ref-conceptual/overview/onenote-add-ins-javascript-reference.md, docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md
Relationships aren't a concept in the new reference docs. Updating the overviews to reflect the information we're now presenting.
=> Removing the term "relationship" from the overviews

generate-docs/GenerateDocs.cmd
Add logic to remove the `node_modules` folder at the very start of the script, since this step seems necessary in order to reliably pick up any changes that have been made to API Documenter and API Extractor.
=> Update GenerateDocs script

docs/docs-ref-conceptual/requirement-sets/identity-api-requirement-sets.md
We don't have an official reference page for this preview API, so I'm relinking it to the longer doc describing behavior.
This is in response to Issue #179.
=> Linking Auth information to conceptual doc

generate-docs/scripts/preprocessor.ts
Updated preprocessor script to clean up recent changes that were implemented to add processing logic for Custom Functions and Office Runtime d.ts files.
- updated initial prompt (for the source of d.ts) to clarify that it's asking for the source of **office.d.ts**
- removed prompts about whether to process Custom Functions d.ts file and Office Runtime d.ts file (they'll be processed by **GenerateDocs.cmd** regardless of how the user answers these prompts, so the prompts are useless)
- added prompts to confirm source of the Custom Functions d.ts file and the Office Runtime d.ts file
- refactored/simplified logic for processing the Custom Functions d.ts file and Office Runtime d.ts file
- moved the logic for processing the Custom Functions and Office Runtime d.ts files to immediately follow …
=> Update preprocessor script

docs/docs-ref-conceptual/requirement-sets/excel-api-requirement-sets.md
Adding the relative link extensions to the What's New section.
Also adjusting createWorkbook (it's part of the Excel object) and removing the non-existent additions to WorkbookCreated.
=> Cleaning up method links for Excel 1.8 APIs

docs/docs-ref-autogen/toc.yml, generate-docs/scripts/postprocessor.ts
Rather than having Custom functions runtime and Office runtime at the root of the ToC, this puts them under their own folder in Excel.
[Here's a link to see the new ToC in action](https://review.docs.microsoft.com/en-us/javascript/api/custom-functions-runtime/customfunctions.cancelablehandler?view=office-js&branch=AlexJ-TOC).
=> [IA] (ToC) Putting custom functions libraries under Excel

generate-docs/tools/WhatsNew.ts, generate-docs/tools/tslint.json
This update improves the tool to link fields to their entries in the reference docs. It also improves the field tables, removes *LoadOptions, and fixes bugs around unioned types.
[Here's a sample docs build](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets?branch=AlexJ-WhatsNew#whats-in-the-excel-javascript-api-preview).
=> [tools] (WhatsNew) Linking fields

generate-docs/tools/.gitignore, generate-docs/tools/WhatsNew.ts, generate-docs/tools/package.json, generate-docs/tools/tsconfig.json
This changes the WhatsNew tool to have a similar compilation pattern as the rest of the repo. It also now pulls directly from DefinitelyTyped (or a local file) and automatically reduces the scope to the selected host.
I've also confirmed the output hasn't been affected by this change.
=> Streamlining WhatsNew experience

generate-docs/tools/VersionRemover.ts
I developed this little tool while working on the preview doc sets, but I think it has value outside of that (particularly with versioning on the horizon). The tool goes through a d.ts file and removes any classes, enums, interfaces, or fields with the specified API set.
=> A tool to remove an API set from a d.ts file

docs/code-snippets/excel-snippets.yaml, docs/docs-ref-autogen/excel/excel.chart.yml, docs/docs-ref-autogen/excel/excel.chartcollection.yml, docs/docs-ref-autogen/excel/excel.worksheet.yml, docs/docs-ref-autogen/outlook/office.appointmentcompose.yml, docs/docs-ref-autogen/outlook/office.appointmentread.yml, docs/docs-ref-autogen/outlook/office.item.yml, docs/docs-ref-autogen/outlook/office.mailbox.yml, docs/docs-ref-autogen/outlook/office.messagecompose.yml, docs/docs-ref-autogen/outlook/office.messageread.yml, generate-docs/api-extractor-inputs-office/office.d.ts, generate-docs/api-extractor-inputs-outlook/outlook.d.ts, generate-docs/json/outlook.api.json, generate-docs/json/snippets.yaml, generate-docs/script-inputs/local-repo-snippets.yaml, generate-docs/script-inputs/office.d.ts
At the request of the product team, here are a few small snippets showing event usage with Excel objects. This is to compensate for the lack of cross-linking support to EventHandler objects in the return type of those events.
=> Adding Excel event snippet examples

generate-docs/scripts/package-lock.json, generate-docs/scripts/package.json
Reviewers, 
GitHub is telling us that there’s a “low severity” security problem with a version of lodash that our simple-prompts.ts uses.  I’ve made the fix in the branch lodash-version-update, but the script should be tested to ensure that the new version of lodash doesn’t break (almost zero chance of this), and I’m not familiar enough with simple-prompts.ts to know whether I’m testing it in the right ways. Please test that branch, and merge to master if it works.
=> Lodash version update

docs/docfx.json
This should restore the links in Outlook (and elsewhere).
[Staging site link](https://review.docs.microsoft.com/en-us/javascript/api/outlook/office.diagnostics?view=office-js&branch=jmazzotta-patch-2)
=> Update docfx to use dfm engine

docs/docs-ref-autogen/excel/excel.shape.yml, docs/docs-ref-autogen/office.yml, docs/docs-ref-autogen/office/office.auth.yml, docs/docs-ref-autogen/office/office.authoptions.yml, docs/docs-ref-autogen/office/office.context.yml, docs/docs-ref-autogen/office/office.document.yml, docs/docs-ref-autogen/toc.yml, generate-docs/api-extractor-inputs-office/office.d.ts, generate-docs/json/office.api.json, generate-docs/json/snippets.yaml, generate-docs/script-inputs/office.d.ts, generate-docs/script-inputs/office_preview.d.ts, generate-docs/script-inputs/script-lab-snippets.yaml, generate-docs/scripts/preprocessor.ts
This switches the Common API source to office-js-preview, instead of office-js. It also gets the latest from Definitely Typed and office-js-snippets.
=> Updating docs and pulling in Common API preview

docs/docfx.json
[Staging site](https://review.docs.microsoft.com/en-us/javascript/api/office?view=office-js&branch=AlexJ-MD).
This changes the OPS build to use the current MarkDig parsing engine, instead of the obsolete one. All the HTML/Markdown conflicts should be resolved and this shouldn't cause any visual changes.
=> Switching to MarkDig parser

docs/code-snippets/word-snippets.yaml, docs/docs-ref-autogen/word/word.contentcontrol.yml
According to the specs (and the rest of the document) the options are:
The value can be 'Replace', 'Start', or 'End'.
Replace should be the 'enum' Replace vs replace used in the example. Fixed this to Uppercase (Scriptlab will otherwise give an error)
=> insertText second parameter should be uppercase

generate-docs/api-extractor-inputs-custom-functions-runtime/api-extractor.json, generate-docs/api-extractor-inputs-excel-release/api-extractor.json, generate-docs/api-extractor-inputs-excel/api-extractor.json, generate-docs/api-extractor-inputs-office-runtime/api-extractor.json, generate-docs/api-extractor-inputs-office/api-extractor.json, generate-docs/api-extractor-inputs-onenote/api-extractor.json, generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_1/api-extractor.json, generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_2/api-extractor.json, generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_3/api-extractor.json, generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_4/api-extractor.json, generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_5/api-extractor.json, generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_6/api-extractor.json, generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_7/api-extractor.json, generate-docs/api-extractor-inputs-outlook/api-extractor.json, generate-docs/api-extractor-inputs-powerpoint/api-extractor.json, generate-docs/api-extractor-inputs-visio/api-extractor.json, generate-docs/api-extractor-inputs-word/api-extractor.json, generate-docs/json/snippets.yaml, generate-docs/package.json, generate-docs/script-inputs/script-lab-snippets.yaml
These warnings come about because of our file splitting. There's also some TSDOC warnings that don't have an effect on the end documentation.
=> Suppress inaccurate warnings from API Extractor

docs/code-snippets/office-snippets.yaml, generate-docs/json/snippets.yaml, generate-docs/script-inputs/local-repo-snippets.yaml, generate-docs/scripts/preprocessor.ts
I don't believe we'll ever not include the Script Lab snippets at this point, so I removed the option from the build script.
=> Removing old cast snippet and forcing SL snippet addition

generate-docs/json/outlook_1_7/Outlook.api.json, generate-docs/scripts/preprocessor.ts
Now that Outlook's preview content is out of DefinitelyTyped/office-js, the preprocessor can generate different docs based on preview and release.
Note that this PR is dependent on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37564 for the upstream content changes.
=> Have Outlook release use office-js instead of office-js-preview

generate-docs/GenerateDocs.cmd, generate-docs/api-extractor-inputs-outlook-release/Outlook_1_1/Outlook.d.ts, generate-docs/api-extractor-inputs-outlook-release/Outlook_1_2/Outlook.d.ts, generate-docs/api-extractor-inputs-outlook-release/Outlook_1_3/Outlook.d.ts, generate-docs/api-extractor-inputs-outlook-release/Outlook_1_4/Outlook.d.ts, generate-docs/api-extractor-inputs-outlook-release/Outlook_1_5/Outlook.d.ts, generate-docs/api-extractor-inputs-outlook-release/Outlook_1_6/Outlook.d.ts, generate-docs/scripts/versioned-dts-cleanup.ts
At some point, I'll need to update the version remover to remove extra blank space. For now, the d.ts files that are generated should otherwise match the hand edited ones. I've also added a way to adjust d.ts files between versions, if needed.
=> [outlook] Autogenerating Outlook legacy version d.ts files

generate-docs/tools/dts-utilities.ts
Links for the markdown table should not include the `...` in those method signatures.
=> [tools] (What's New) Stripping repeated parameter notation from markdown links

generate-docs/package.json
We're unable to switch to API Documenter 7.7, so I'm removing the "get latest version" flags from the package file.
=> Locking version of API Documenter

DocumentationToolingNotes.md, generate-docs/scripts/preprocessor.ts
This reduces the prompts asked when generating the docs from four to one. It also adds an explanation about creating docs from local files and the review site.
=> Simplify preprocessor prompts

docs/docs-ref-autogen/overview/overview.md
PPT has been getting active investment in APIs lately. To better show this, this PR updates the reference overview page to sort the Office applications in order of API support.
=> Reorder PPT on the reference overview page

generate-docs/GenerateDocs.cmd, generate-docs/scripts/package-lock.json, generate-docs/scripts/package.json
No longer needed since udp -> sdp conversion happens in version of Rushstack tools we're on.
=> [Admin] Remove sdp tool

docs/docfx.json
Review site: https://review.docs.microsoft.com/en-us/javascript/api/overview?view=excel-js-preview&branch=AlexJ-Visio
The Common APIs were still being included in the visio-1.1 moniker, despite not being in the TOC. This PR cleans up the moniker story to make the separation.
=> [monikers] Decouple the Common APIs from Visio

.openpublishing.publish.config.json, docs/docfx.json, docs/docs-ref-autogen/common_preview/toc.yml, docs/docs-ref-autogen/office/office/office.addin.yml, docs/docs-ref-autogen/office/office/office.beforedocumentclosenotification.yml, docs/docs-ref-autogen/office_release/office/office.addin.yml, generate-docs/api-extractor-inputs-office-release/office.d.ts, generate-docs/api-extractor-inputs-office/office.d.ts, generate-docs/json/office/office.api.json, generate-docs/json/office_release/office.api.json, generate-docs/scripts/postprocessor.ts, generate-docs/tools/API Coverage Report.csv
[Staging site](https://review.docs.microsoft.com/en-us/javascript/api/overview?view=common-js-preview&branch=AlexJ-CommonMoniker). 
This PR adds moniker support for preview vs release Common APIs. Note that the version name of the release common APIs needs to be changed from "Common" to "Release". The request for that is [active](https://ceapex.visualstudio.com/Onboarding/_workitems/edit/527730).
The easiest test case is the [BeforeDocumentCloseNotification](https://review.docs.microsoft.com/en-us/javascript/api/office/office.beforedocumentclosenotification?view=common-js-preview&branch=AlexJ-CommonMoniker) class in the preview Common APIs.
=> [versioning] (Common APIs) Adding common preview moniker support

generate-docs/GenerateDocs.cmd
Most of the sub-scripts and tools log enough status while GenerateDocs.cmd is running. However, API Extractor doesn't provide any context as to what API set it's working on. Since this is the longest part of the process, it can become unclear where the script is in execution. This PR should also help with future debugging and improvements.
=> [scripts] (GenerateDocs) Adding log statements to the build file

docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
The shared mailbox add-in feature is in preview on Outlook on Windows and on Mac at this time.
=> [Outlook] (shared mailbox) Remove OWA support for shared mailbox feature

docs/manifest/customtab.md, docs/manifest/extensionpoint.md, docs/manifest/group.md, docs/manifest/overriddenbyribbonapi.md
There is a corresponding PR in the conceptual docs repo that has the same purpose.
=> [All Hosts] (ui) clarify that add-in can have only 1 custom tab

docs/manifest/rule.md
In response to a [forum post](https://stackoverflow.com/questions/73088079/outlook-add-in-regular-expression-works-on-body-but-not-on-subject) and internal bug 165177.
=> [All hosts] (manifest) Clarify use of Highlight attribute

docs/requirement-sets/outlook/preview-requirement-set/office.context.mailbox.item.md, docs/requirement-sets/outlook/preview-requirement-set/office.context.md, docs/requirement-sets/outlook/requirement-set-1.1/office.context.md, docs/requirement-sets/outlook/requirement-set-1.10/office.context.mailbox.item.md, docs/requirement-sets/outlook/requirement-set-1.10/office.context.md, docs/requirement-sets/outlook/requirement-set-1.11/office.context.mailbox.item.md, docs/requirement-sets/outlook/requirement-set-1.11/office.context.md, docs/requirement-sets/outlook/requirement-set-1.12/office.context.md, docs/requirement-sets/outlook/requirement-set-1.2/office.context.md, docs/requirement-sets/outlook/requirement-set-1.3/office.context.md, docs/requirement-sets/outlook/requirement-set-1.4/office.context.md, docs/requirement-sets/outlook/requirement-set-1.5/office.context.md, docs/requirement-sets/outlook/requirement-set-1.6/office.context.md, docs/requirement-sets/outlook/requirement-set-1.7/office.context.md, docs/requirement-sets/outlook/requirement-set-1.8/office.context.md, docs/requirement-sets/outlook/requirement-set-1.9/office.context.md
- Addresses `displayLanguage` formatting suggestion from #1387.
- Adds `InfobarClicked` event to applicable requirement set Office.context.mailbox.item pages.
=> [Outlook] (requirement sets) Fix format and update Events table

docs/manifest/extendedpermission.md
Corrects the specified value of the **\<ExtendedPermission>** element for the prepend-on-send feature.
=> [Outlook] (prepend-on-send) Correct the specified manifest permission

docs/manifest/image.md, docs/manifest/images.md, docs/manifest/longstrings.md, docs/manifest/manifest.md, docs/manifest/override.md, docs/manifest/resources.md, docs/manifest/shortstrings.md, docs/manifest/string.md, docs/manifest/toc.yml, docs/manifest/url.md, docs/manifest/urls.md
Every element that can have child elements, should have it's own page. For some reason, the ones created in this PR were never created. 
Also updates the Override topic with more possible parent elements, and moves content out of the Resources topic to the new articles.
=> [All Hosts] (manifest) adds missing reference articles

docs/requirement-sets/common/add-in-commands-requirement-sets.md, docs/requirement-sets/outlook/requirement-set-1.3/outlook-requirement-set-1.3.md
The corollary PR to https://github.com/OfficeDev/office-js-docs-pr/pull/3907. This adjusts the links to match what will be in the other repo.
=> [all hosts] (Add-in Commands) Update command docs links

docs/includes/using-preview-apis-host.md, docs/requirement-sets/excel/excel-api-requirement-sets.md, docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md, docs/requirement-sets/word/word-api-requirement-sets.md
The Office Insider program is now referred to as the Microsoft 365 Insider program (https://insider.microsoft365.com/). This PR updates references in our documentation.
=> [All hosts] (insider program) Update Office Insider references

docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Adds additional message properties returned by the `getSelectedItemsAsync` method to the preview page. The link to the Office.SelectedItemDetails page should be resolved after merging DT changes and running the reference build script.
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65784
=> [Outlook] (multi-select) Add additional message properties in preview

.openpublishing.redirection.json
IIRC, docs-ref-autogen entries were never real files but an artifact of the migration from dev.office.com back in 2018.
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4063
=> [all hosts] Clean up redirects

docs/manifest/launchevent.md, docs/requirement-sets/outlook/requirement-set-1.12/outlook-requirement-set-1.12.md
- Moves the list of send mode options to the conceptual repository.
- Adds a link to the new location. (Redirection to the appropriate section will be resolved once the conceptual PR is merged. See https://github.com/OfficeDev/office-js-docs-pr/pull/4080.)
=> [Outlook] (Smart Alerts) Rewrite send mode options

docs/includes/runtimes-note.md, docs/manifest/customfunctionssourcelocation.md, docs/manifest/extensionpoint.md, docs/manifest/moreinfo.md, docs/manifest/override.md, docs/manifest/preprocessingdialog.md, docs/manifest/reportingoptions.md, docs/manifest/reportphishingcustomization.md, docs/manifest/runtime.md, docs/manifest/runtimes.md, docs/manifest/string.md, docs/manifest/toc.yml, docs/manifest/url.md, docs/requirement-sets/outlook/preview-requirement-set/office.context.mailbox.item.md, docs/requirement-sets/outlook/preview-requirement-set/office.md, docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
- Documents the XML manifest elements needed to implement the spam reporting feature.
- Adds the integrated spam reporting feature to the preview page.
Related PRs:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66028
- https://github.com/OfficeDev/office-js-docs-pr/pull/4102
- https://github.com/OfficeDev/office-js-snippets/pull/802
=> [Outlook] (spam reporting) Document spam reporting manifest elements

docs/requirement-sets/outlook/preview-requirement-set/office.md, docs/requirement-sets/outlook/requirement-set-1.10/office.md, docs/requirement-sets/outlook/requirement-set-1.11/office.md, docs/requirement-sets/outlook/requirement-set-1.12/office.md, docs/requirement-sets/outlook/requirement-set-1.13/office.md
Updates the EventType table in the requirement set pages based on [Office.EventType](https://learn.microsoft.com/javascript/api/office/office.eventtype).
=> [Outlook] (events) Add missing events

docs/code-snippets/office-snippets.yaml, docs/docs-ref-autogen/office/office/office.addincommands.eventcompletedoptions.yml, docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md, generate-docs/json/office/snippets.yaml, generate-docs/json/office_release/snippets.yaml, generate-docs/json/snippets.yaml, generate-docs/script-inputs/local-repo-snippets.yaml
- Adds Office.MailboxEnums.MoveSpamItemTo to the Outlook preview page.
- Updates snippets to use the enum.
Related PRs:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66280
- https://github.com/OfficeDev/office-js-docs-pr/pull/4125
=> [Outlook] (spam reporting) Add enum support

docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Adds a hyphen to "spam-reporting feature" for consistency.
=> [Outlook] (spam reporting) Minor formatting fix

generate-docs/package-lock.json, generate-docs/scripts/package-lock.json, generate-docs/tools/API Coverage Report.csv, generate-docs/tools/coverage-tester.ts, generate-docs/tools/package-lock.json
In order to better understand our sample coverage, we should ignore deprecated APIs. This PR adjusts the coverage tester to note that.
=> [tools] (coverage-tester) Updating coverage tester to denote deprecated APIs

docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Adds the Smart Alerts dialog button customization and send mode override features to the Outlook preview page.
Related PRs:
- https://github.com/OfficeDev/office-js-docs-pr/pull/4152
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66521
=> [Outlook] (Smart Alerts) Add dialog button customization and send mode override features

docs/code-snippets/outlook-snippets.yaml, docs/docs-ref-autogen/outlook/outlook/office.mailbox.yml, docs/docs-ref-autogen/outlook_1_13/outlook/office.mailbox.yml, generate-docs/API Coverage Report.csv, generate-docs/json/outlook/snippets.yaml, generate-docs/json/outlook_1_1/snippets.yaml, generate-docs/json/outlook_1_10/snippets.yaml, generate-docs/json/outlook_1_11/snippets.yaml, generate-docs/json/outlook_1_12/snippets.yaml, generate-docs/json/outlook_1_13/snippets.yaml, generate-docs/json/outlook_1_2/snippets.yaml, generate-docs/json/outlook_1_3/snippets.yaml, generate-docs/json/outlook_1_4/snippets.yaml, generate-docs/json/outlook_1_5/snippets.yaml, generate-docs/json/outlook_1_6/snippets.yaml, generate-docs/json/outlook_1_7/snippets.yaml, generate-docs/json/outlook_1_8/snippets.yaml, generate-docs/json/outlook_1_9/snippets.yaml, generate-docs/json/snippets.yaml, generate-docs/script-inputs/local-repo-snippets.yaml
Removes the existing code snippet from `getSelectedItemsAsync` as it will be replaced with a Script Lab snippet (see https://github.com/OfficeDev/office-js-snippets/pull/822).
=> [Outlook] (multi-select) Remove existing code snippet from getSelectedItemsAsync

docs/manifest/control-button.md, docs/manifest/control-menu.md, docs/manifest/supertip.md
Adds a note to applicable pages that supertips aren't supported in Office on the web.
=> [All hosts] (manifest) Add note on supertip support in Office on the web

.gitignore, generate-docs/GenerateDocs.sh
It's hard to notice warnings that happen in the middle of the build process. This PR logs the text output from the build process to a pair of files: one general log and one for warnings and errors. Everything still goes to the console too.
=> [scripts] Output build process console output to log files

docs/requirement-sets/excel/custom-functions-requirement-sets.md
A license check has been removed for Custom Functions. This PR updates the Excel versions that now support the feature on perpetual versions of Office.
=> [excel] (Custom Functions) Update custom function requirement sets

docs/docfx.json
Fixes `ms.devlang` value to comply with the [taxonomy list](https://review.learn.microsoft.com/help/platform/metadata-taxonomies?branch=main#msdevlang).
=> [All hosts] (metadata) Fix ms.devlang value

docs/manifest/formsettings.md
Adds information about the **\<FormSettings>** element from the soon-to-be-retired Outlook manifests conceptual article.
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4365
=> [Outlook] (manifest) Add information about the FormSettings element

docs/code-snippets/office-snippets.yaml
`Office.CoercionType` is the most viewed reference page without any samples. This should fix that.
=> [all hosts] (Common) Add a CoercionType snippet

docs/requirement-sets/outlook/requirement-set-1.1/outlook-requirement-set-1.1.md, docs/requirement-sets/outlook/requirement-set-1.6/outlook-requirement-set-1.6.md
Related to the change made in https://github.com/OfficeDev/office-js-docs-reference/pull/1795. Adds the retirement note to other pages based on feedback.
=> [Outlook] (contextual add-in) Add retirement note

docs/includes/outlook-contextual-add-ins-retirement.md
Specifies when entity-based contextual Outlook add-ins will be retired and indicates which APIs will be affected.
Related PRs:
- https://github.com/OfficeDev/office-js-docs-pr/pull/4412
=> [Outlook] (contextual add-ins) Clarify retirement timeline

docs/requirement-sets/outlook/outlook-api-requirement-sets.md
Also swaps the order of the XML and unified tabs.
=> [Outlook] (manifest) remove preview lingo for unified manifest

docs/code-snippets/office-snippets.yaml, docs/code-snippets/powerpoint-snippets.yaml, docs/docs-ref-autogen/office/office/officeextension.clientobject.yml, docs/docs-ref-autogen/office/office/officeextension.clientresult.yml, docs/docs-ref-autogen/office_release/office/officeextension.clientobject.yml, docs/docs-ref-autogen/office_release/office/officeextension.clientresult.yml, docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.requestcontext.yml, docs/docs-ref-autogen/powerpoint_1_1/powerpoint/powerpoint.requestcontext.yml, docs/docs-ref-autogen/powerpoint_1_2/powerpoint/powerpoint.requestcontext.yml, docs/docs-ref-autogen/powerpoint_1_3/powerpoint/powerpoint.requestcontext.yml, docs/docs-ref-autogen/powerpoint_1_4/powerpoint/powerpoint.requestcontext.yml, docs/docs-ref-autogen/powerpoint_1_5/powerpoint/powerpoint.requestcontext.yml, generate-docs/API Coverage Report.csv, generate-docs/script-inputs/local-repo-snippets.yaml
These pages have relatively high traffic and could use some sample code to show how the object model works.
=> [WXP] Adding basic samples around OfficeExtension objects

docs/docs-ref-autogen/office/office/office.tablebinding.yml, docs/docs-ref-autogen/office_release/office/office.tablebinding.yml, docs/manifest/extensionpoint.md, docs/manifest/officemenu.md, generate-docs/api-extractor-inputs-office-release/office.d.ts, generate-docs/api-extractor-inputs-office/office.d.ts
Update according to [current guidance](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/r/right-click) so instruction isn't mouse-centric.
=> [all hosts] Update references to right-click

docs/manifest/officetab.md
In conjunction with [4692](https://github.com/OfficeDev/office-js-docs-pr/pull/4692) in the conceptual repo, this moves the list of built-in Office tab IDs to a separate article that can be linked to from this one and from the unified manifest reference. Also, some other minor fixes.
=> [All Hosts] (ui) move list of built-in tab IDs to other article

docs/manifest/control-button.md, docs/manifest/control-menu.md, docs/manifest/extensionpoint.md, docs/manifest/group.md
Fixes a verbatim in conjunction with a correlative PR in the -pr repo. The `<Tooltip>` element is only supported in Outlook and only as a child of the `<Group>` element.
=> [All Hosts] (manifest) Tooltip only supported in Outlook Group

docs/manifest/launchevent.md
Clarifies location of supported event types to use with the LaunchEvent element based on user feedback.
=> [Outlook] (manifest) Clarify location of supported event types

docs/manifest/action.md, docs/requirement-sets/common/add-in-commands-requirement-sets.md, docs/requirement-sets/common/dialog-api-requirement-sets.md, docs/requirement-sets/common/dialog-origin-requirement-sets.md, docs/requirement-sets/common/identity-api-requirement-sets.md, docs/requirement-sets/common/keyboard-shortcuts-requirement-sets.md, docs/requirement-sets/common/open-browser-window-api-requirement-sets.md, docs/requirement-sets/common/ribbon-api-requirement-sets.md, docs/requirement-sets/common/shared-runtime-requirement-sets.md, docs/requirement-sets/excel/custom-functions-requirement-sets.md, docs/requirement-sets/excel/excel-api-requirement-sets.md, docs/requirement-sets/powerpoint/powerpoint-api-requirement-sets.md, docs/requirement-sets/word/word-api-requirement-sets.md
Format is based on [Update history for Office for Mac](https://learn.microsoft.com/officeupdates/update-history-office-for-mac).
Related PRs:
https://github.com/OfficeDev/office-js-docs-pr/pull/4790
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70501
=> [All hosts] Make the format of Office on Mac versions consistent

docs/requirement-sets/outlook/preview-requirement-set/office.context.mailbox.md, docs/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview.md
Related PRs:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69930
- https://github.com/OfficeDev/office-js-docs-pr/pull/4739
=> [Outlook] (multi-select) Document multi-select improvements

docs/requirement-sets/excel/excel-api-requirement-sets.md, docs/requirement-sets/outlook/outlook-api-requirement-sets.md, docs/requirement-sets/word/word-api-requirement-sets.md
Reverts https://github.com/OfficeDev/office-js-docs-reference/pull/2084 based on internal guidance.
=> [All hosts] Revert previous change to CDN URL

docs/manifest/appdomain.md
Applies to Outlook on the web and new Outlook on Windows.
Fixes https://github.com/OfficeDev/office-js/issues/3926.
=> [Outlook] (manifest) Update localhost guidance for AppDomain element

docs/requirement-sets/outlook/preview-requirement-set/office.md
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71472
=> [Outlook] (events) Document InitializationContextChanged event

docs/toc.yml
This doesn't need a review. These two elements are also in the TOC under VersionOverrides which is the only place where they should be in the TOC.
=> [All Hosts] (manifest) remove redundant entries in TOC

docs/manifest/versionoverrides-1-0-content.md, docs/manifest/webapplicationinfo.md
Fixes [2273](https://github.com/issues/assigned?issue=OfficeDev%7Coffice-js-docs-reference%7C2273)
=> [All Hosts] (auth) specify location of WebApplicationInfo element

docs/manifest/equivalentaddins.md
Merge at public preview. Should be 7/21/25
=> [All Hosts] (installation) Preview control of choice for COM or Office add-in
